services:
  nginx:
    image: lukas1h07/nginx-http-flv-module:latest

    expose:
      - "80"
      - "1935"
    volumes:
      - ./setup/conf/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock

    entrypoint: [ "/bin/sh", "/etc/nginx/entrypoint.sh" ]
    container_name: nginx
