services:

  app-server:
    build: ./dashboard
    image: dashboard:1.0.0
    stdin_open: true
    ports:
      - "80:3000"
    container_name: dashboard
    volumes:
      - ./setup/:/setup
      # - ./dashboard:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    # command: npm run

  nginx:
    build: ./nginx
    ports:
      - "1935:1935" # RTMP input
    expose:
      - "80"
      - "1935"

    volumes:
      - ./setup/conf/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock

    entrypoint: [ "/bin/sh", "/etc/nginx/entrypoint.sh" ]
    container_name: nginx

  stunnel:
    build: ./stunnel
    expose:
      - "1935" # Youtube RTMP input
      - "1936" # Facebook RTMP input
      - "1937" # Instagram RTMP input
    volumes:
      # - ./stunnel/stunnel.conf:/etc/conf/stunnel.conf
      # - ./setup/conf/stunnel.conf:/etc/stunnel/stunnel.conf
      - /var/run/docker.sock:/var/run/docker.sock

    # entrypoint: [ "/bin/bash", "/etc/stunnel/entrypoint.sh" ]
    container_name: stunnel
  fallback:
    build: ./fallback
    expose:
      - "80"
    container_name: fallback
